//
// Created by Faisal Javed on 30/09/22.
//

#ifndef GRADINGASSIGNMENT_CS700_MAIN_SECTION2_H
#define GRADINGASSIGNMENT_CS700_MAIN_SECTION2_H


class main_section2 {

};


#endif //GRADINGASSIGNMENT_CS700_MAIN_SECTION2_H
